# Want more configurability? Let me know in our Discord or in the resource discussion section!


# If we should register this addon's commands as a brewery subcommand or
# its own command registered on behalf of Brewery
# Subcommand: /brewery recipes <args>
# Command: /breweryrecipes <args>
# Requires a server restart to take effect
use-brewery-subcommand: true
# The main permission node for commands is brewery.cmd.recipes
command-permissions:
  givebook: "breweryrecipes.givebook"
  give: "breweryrecipes.give"
  gui: "breweryrecipes.gui"

# Recipes can be stored to a player via 2 methods:
# Permission_API, Command
# When using native permissions, BreweryRecipes will save update the player's permissions
# via the permission plugin's API
# When using COMMAND, BreweryRecipes will run the command specified in the command field
recipe-saving-method: Command

# Currently only supports: LuckPerms
permissions-api-plugin: LuckPerms

# The command to run when using COMMAND as the recipe-saving-method
permission-command: "lp user %player% permission set %permission% %boolean%"
permission-unset-command: "lp user %player% permission unset %permission%"

recipe-permission-node: "breweryrecipes.recipe.%recipe%"

# Recipes spawn in loot chests randomly throughout the world
# Disable this by setting your chance to -1
recipe-spawning:
  bound: 100 # The highest value that the random number can generate to. Ex: 100 means a random number between 0 and 100
  chance: 15 # The chance that a recipe will spawn in a loot chest


recipe-book-item:
  material: BOOK
  display_name: '&6&lRecipe Book'
  lore: [ '&7Right-Click to open your', '&7recipe book!' ]
  glint: true

# The physical recipe item that will spawn in loot chests
recipe-item:
  material: PAPER
  name: '&#F7FFC9%recipe% &fRecipe'
  lore: [ '&7Right-Click to redeem', '&7this recipe!' ]
  glint: true

# Full example Gui Border Item
# item:
#   material: GRASS
#   slots: [ 0 ]
#   display_name: 'example item'
#   lore: [ 'example lore', 'another line' ]
#   glint: true
#   custom_model_data: -1
gui:
  title: '&#f670f1&lR&#dd7af6&le&#c584fa&lc&#ac8eff&li&#9c92ff&lp&#8d96ff&le&#7d9aff&ls'
  size: 54
  items:
    recipe-item-slots: [19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34]
    total_recipes:
      material: BOOK
      slots: [ 49 ]
      display_name: '&#f498f6Total Recipes&7: &e%total_recipes%'
      glint: true
    next_page:
      material: ARROW
      slots: [ 50 ]
      display_name: '&#f498f6Next Page'
      lore: [ ]
    previous_page:
      material: ARROW
      slots: [ 48 ]
      display_name: '&#f498f6Previous Page'
      lore: [ ]
  border-items:
    # Border items
    border1:
      material: GREEN_STAINED_GLASS_PANE
      slots: [ 0, 8, 45, 53 ]
      display_name: '&0'
    border2:
      material: GRASS
      slots: [ 1, 7, 46, 52 ]
      display_name: '&0'
    border3:
      material: FERN
      slots: [ 2, 6, 47, 51 ]
      display_name: '&0'
    border4:
      material: PINK_TULIP
      slots: [ 3, 5, 48, 50 ]
      display_name: '&0'
    border5:
      material: LILY_PAD
      slots: [ 4, 49 ]
      display_name: '&0'

# Version for if/when I update the config to have more options
version: '1.0-BETA'